Vagrant.configure("2") do |config|
    
    config.vm.box = "ubuntu/bionic64"

    config.vm.boot_timeout = 600

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "256"
    vb.cpus = 1
  end

  
  config.vm.network "private_network", type: "dhcp"

  
  config.vm.synced_folder "./html", "/var/www/html"

  
  config.vm.provision "shell", inline: <<-SHELL
   
    sudo apt-get update
    sudo apt-get install -y apache2
    sudo systemctl enable apache2
    sudo systemctl start apache2
  SHELL
end